SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('posts.urls'), name = 'posts-url'),
    path('accounts/', include('allauth.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, favourite_add, favourites_list, newest_posts

urlpatterns = [
    path('myfeed/', post_comment_create_and_list_view, name='main-post-view'),
    path('', newest_posts, name='newest-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('fav/<int:id>/', favourite_add, name='favourite-add'),
    path('favourites/',favourites_list, name='favourites-list')
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    ProfileListView,
    send_invitation, remove_from_friends,
    reject_invitation, accept_invitation,
    ProfileDetailView, FriendsListView
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('my-friends/', FriendsListView.as_view(), name='my-friends-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse

from .utils import get_random_code
# Create your models here.
class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = []
        for rel in qs:
            if rel.status == 'accepted':
                accepted.append(rel.receiver)
                accepted.append(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]

        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles
    def get_all_friends(self, me):
        profile = Profile.objects.get(user=me)
        list_of_ids = me.friends.all().values_list('id', flat=True)
        qs = Profile.objects.filter(id__in=[list_of_ids])
        return qs
        

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.FileField(default='avatar.jpg', upload_to='avatars/')

    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()
    def get_absolute_url(self):
        return reverse('profiles:profile-detail-view', kwargs={'slug': self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_image_url(self):
        return self.image.url

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def __str__(self):
        return f'{self.user.username} -- {self.created.strftime("%d-%m-%Y")}'

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)
STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)
class RelationShipManager(models.Manager):
    def invitation_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs



class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationShipManager()
    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.models import User


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

profiles/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404, reverse

from posts.models import Post
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from posts.forms import CommentModelForm
# Create your views here.

@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    posts = Post.objects.filter(author=profile)
    confirm = False
    c_form = CommentModelForm()

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()
    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
        'posts': posts,
        'c_form': c_form,
    }

    return render(request, 'profiles/myprofile.html', context)

@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitation_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False

    if len(results) == 0:
        is_empty = True

    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/my_invites.html', context)
@login_required
def accept_invitation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')

@login_required
def reject_invitation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()

    return redirect('profiles:my-invites-view')


class ProfileDetailView(LoginRequiredMixin,DetailView, FormMixin):
    model = Profile
    template_name = 'profiles/detail.html'
    form_class = CommentModelForm

    def get_success_url(self):
        profile = self.get_object()
        return '{}'.format(reverse('profiles:profile-detail-view', kwargs={'slug': profile.slug}))
    
    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        friends = Profile.objects.get_all_friends(self.get_object().user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        context['c_form'] = CommentModelForm()
        context['profiles'] = friends
        context['is_empty'] = False
        if len(friends) == 0:
            context['is_empty'] = True
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = Profile.objects.get(id=self.request.user.id)
        instance.post = Post.objects.get(id=self.request.POST.get('post_id'))
        instance.save()
        return super().form_valid(form)

class FriendsListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        qs = Profile.objects.get_all_friends(self.request.user)
        return qs

class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'profiles'

    def get_template_names(self):
        template_name = super(ProfileListView, self).get_template_names()
        search = self.request.GET.get('q')
        if search:
            template_name = 'search.html'
        return template_name

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, word=None, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get('q')
        if word:
            search = word
        if search:
            context['profiles'] = Profile.objects.all().filter(Q(first_name__icontains=search) | Q(last_name__icontains=search) | Q(user__username__icontains=search))
            return context
        else:
            profile = Profile.objects.get(user=self.request.user)
            rel_r = Relationship.objects.filter(sender=profile)
            rel_s = Relationship.objects.filter(receiver=profile)
            rel_receiver = []
            rel_sender = []
            for item in rel_r:
                rel_receiver.append(item.receiver.user)
            for item in rel_s:
                rel_sender.append(item.sender.user)
            context['rel_receiver'] = rel_receiver
            context['rel_sender'] = rel_sender
            context['is_empty'] = False
            if len(self.get_queryset()) == 0:
                context['is_empty'] = True

            return context

@login_required
def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get((Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)))
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

profiles/templates/profiles/detail.html
{% extends 'base.html' %}
{% block title %}
profile detail
{% endblock %}

{% block content %}
<div class="ui modal mymodal">
    {% if is_empty %}
    <h1>No profiles to interact</h1>
    {% endif %}
    {% for obj in profiles%}
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column">
                    <img class="ui small circular image" src={{ obj.avatar.url}}>
                </div>
                <div class="thirteen wide column">
                    <h3>{{ obj.user }}</h3>
                    <p>{{ obj.bio}}</p>
                    <a href="{{ obj.get_absolute_url }}"><button class="ui primary button mb-5 w-big">See
                            profile</button></a>
                    <br>
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                    <form action="{% url 'profiles:send-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{ obj.pk }}>
                        <button type="submit" class="ui positive basic button mb-5 w-big"><i
                                class="plus square icon"></i>Add to friends</button>

                    </form>
                    {% endif %}
                    {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                    <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                    {% endif %}
                    {% if request.user in obj.friends.all %}
                    <form action="{% url 'profiles:remove-friend'%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{ obj.pk }}>

                        <button type="submit" class="ui negative basic button mb-5 w-big"><i
                                class="minus square icon"></i>Remove from friends</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url }}>
            {% if object.first_name %}
            <h3>{{object.first_name}} {{object.last_name}}</h3>
            {%else%}
            <h1>{{object.user}}</h1>
            {% endif %}
            <p>{{ object.bio }}</p>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_no }}</div>
                </div>
                {% if object.get_friends_no != 0 %}
                <div class="item"> 
                    <button class='ui secondary button' id='modal-btn'>See Friends</button>
                </div>
                {% endif %}
            </div>
            {% if object.user != request.user %}
            {% if object.user not in rel_receiver and object.user not in rel_sender %}
            <form action="{% url 'profiles:send-invite' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value={{ object.pk }}>
                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to
                    friends</button>

            </form>
            {% endif %}
            {% if object.user in rel_receiver and request.user not in object.friends.all %}
            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}
            {% if request.user in object.friends.all %}
            <form action="{% url 'profiles:remove-friend'%}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value={{ object.pk }}>

                <button type="submit" class="ui negative basic button mb-5 w-big"><i
                        class="minus square icon"></i>Remove from friends</button>
            </form>
            {% endif %}
            {% endif %}
        </div>
        <div class="twelve wide column">
            {% if not posts %}
            <div class="ui fluid card">
                <div class="content">
                    <div class="right floated meta">
                        <div class="ui grid">
                            <h1 style="text-align: center;">No posts yet . . .</h1>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% for obj in posts %}

                <div class="ui fluid card">
                    <div class="content">
                        <div class="right floated meta">
                            <div class="ui grid">
                                <div class="row">
                                    {% ifequal request.user obj.author.user %}
                                    <a href="{% url 'post-update' obj.pk %}"><button
                                            class="ui button bwhite-lg ">Update</button></a>
                                    <a href="{% url 'post-delete' obj.pk %}"><button
                                            class="ui button bwhite-lg ">Delete</button></a>
                                    {% endifequal %}
                                </div>
                            </div>

                        </div>
                        <img class="ui avatar image" src={{obj.author.avatar.url}}>
                        <a href="{% url 'profiles:profile-detail-view' obj.author.slug%}">{{ obj.author.user }}</a> -
                        {{ obj.created|timesince}} ago
                    </div>
                    <div class="ui fluid image">
                        {% if obj.image %}
                        <img src={{obj.image.url}}>
                        {% endif %}
                    </div>
                    <div class="content">
                        <p> {{ obj.content }} </p>
                        <div class="right floated">
                            <form action="{% url 'like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{obj.id}}>
                                {% if profile not in obj.liked.all %}
                                <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                                </button>
                                <span> {{obj.num_likes}} likes</span>
                                {% else %}
                                <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                                </button>
                                <span> {{obj.num_likes}} likes</span>
                                {% endif %}
                            </form>
                            <form action="{% url 'like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{obj.id}}>
                                {% if profile not in obj.favorite.all %}
                                <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                                </button>
                                {% else %}
                                <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                                </button>
                                {% endif %}

                            </form>
                            <div class="col-md-7 d-flex justify-content-between">
                                <div>
                                    <a href="{% url 'favourite-add' obj.id %} " class="btn btn-outline-primary">Add to
                                        Favourites</a>
                                </div>
                            </div>
                        </div>

                        <i class="comment icon"></i>
                        <span> {{ obj.num_comments }} comments</span>
                    </div>
                    <div class="extra content">
                        <div class="mb-5">

                        </div>
                        <button class="cmt_btn ui button mb-5">show / hide comments</button>
                        <div class="comment-box">
                            {% if obj.comment_set.all %}
                            {% for c in obj.comment_set.all %}

                            <div class="ui segment mb-5">
                                <img class="ui avatar image" src={{c.user.avatar.url}}>
                                <span>{{ c.user }}</span>
                                <div class='mt-5'>{{ c.body }}</div>
                            </div>

                            {% endfor %}
                            {% endif %}
                        </div>
                        <form action="" method="POST" class='ui fluid form'>
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{obj.id}}>
                            {{ c_form }}
                            <button type="submit" name="submit_c_form"
                                class="ui primary button mt-5 w-full">Send</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock  %}
    {% block scripts %}
    <script>
        $(document).ready(function () {
            let display = false
            $(".cmt_btn").click(function () {
                if (display === false) {
                    $(this).next(".comment-box").show("slow");
                    display = true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display = false
                }
            });
        });
    </script>
    {% endblock scripts %}

profiles/templates/profiles/login.html
{% extends 'base.html' %}
{% block content %}
<form style="color: #fff;" method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No invitations here...</h1>
    {% endif %}`

    {% for obj in qs%}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src="{{obj.avatar.url}}">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{ obj.user }}</h3>
                        <p>{{ obj.bio }}</p>
                        <br>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'profiles:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>Accept invite
                            </button>
                        </form>
                        <form action="{% url 'profiles:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>Reject invite
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
all profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No profiles to interact</h1>
    {% endif %}
    {% for obj in profiles%}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{ obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{ obj.user }}</h3>
                        <p>{{ obj.bio}}</p>
                        <a href="{{ obj.get_absolute_url }}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{ obj.pk }}>
                            <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>

                        </form>
                        {% endif %}
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}
                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend'%}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{ obj.pk }}>

                                <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/registration.html
{% extends 'base.html' %}
{% block content %}
<form style="color: #fff;" method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Sign up</button>
</form>

{% endblock %}