SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('posts.urls'), name = 'posts-url'),
    path('accounts/', include('allauth.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, favourite_add, favourites_list, newest_posts

urlpatterns = [
    path('myfeed/', post_comment_create_and_list_view, name='main-post-view'),
    path('', newest_posts, name='newest-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('fav/<int:id>/', favourite_add, name='favourite-add'),
    path('favourites/',favourites_list, name='favourites-list')
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    ProfileListView,
    send_invitation, remove_from_friends,
    reject_invitation, accept_invitation,
    ProfileDetailView, FriendsListView
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('my-friends/', FriendsListView.as_view(), name='my-friends-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

templates/main/navbar.html
{% url 'main-post-view' as path_to_posts%}
{% url 'newest-post-view' as path_to_newest%}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites%}
{% url 'profiles:invite-profiles-view' as path_to_send_invite%}
{% url 'profiles:all-profiles-view' as path_to_all_profile%}
{% url 'favourites-list' as path_to_my_favourites %}
{% url 'profiles:my-friends-view' as path_to_my_friends %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{ path_to_posts }}" class="item">
        <h3>DevGram</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="item">
        My Feed
    </a>
    <a href="{{path_to_newest}}" class="item">
        Other Posts
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">

                    <a href="{{path_to_all_profile}}" class="item">
                        All Profiles
                    </a>
                    <a href="{{path_to_my_friends}}" class="item">
                        My Friends
                    </a>
                    <a href="{{path_to_my_invites}}" class="item">
                        Received Invites &nbsp; <div class="ui green horizontal label">{{invites_num}}</div>
                    </a>
                    <a href="{{path_to_my_favourites}}" class="item">
                        My Favourite Posts&nbsp;
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="/profiles/" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{ path_to_my_profile }}" class="item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                {{ request.user }}
            </a>

            <a href="{% url 'account_logout'%}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login'%}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>