SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('posts.urls'), name = 'posts-url'),
    path('accounts/', include('allauth.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, favourite_add, favourites_list, newest_posts

urlpatterns = [
    path('myfeed/', post_comment_create_and_list_view, name='main-post-view'),
    path('', newest_posts, name='newest-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('fav/<int:id>/', favourite_add, name='favourite-add'),
    path('favourites/',favourites_list, name='favourites-list')
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    ProfileListView,
    send_invitation, remove_from_friends,
    reject_invitation, accept_invitation,
    ProfileDetailView, FriendsListView
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('my-friends/', FriendsListView.as_view(), name='my-friends-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset()
    content = models.TextField()
    image = models.FileField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)
    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Post
        fields = ('content', 'image')

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment ...'}))

    class Meta:
        model = Comment
        fields  = ('body',)

posts/views.py
from re import search
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse, resolve
# Create your views here.
@login_required
def newest_posts(request):
    qs = Post.objects.all().order_by('-created')
    profile = Profile.objects.get(user=request.user)
    paginator = Paginator(qs, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False

    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()
    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
        'posts': posts
    }
    return render(request, 'posts/main2.html', context)
@login_required
def post_comment_create_and_list_view(request):
    me = Profile.objects.get(user=request.user)
    list_of_ids = me.friends.all().values_list('id', flat=True)
    lst = [i for i in list_of_ids]
    lst.append(me.id)
    qs = Post.objects.all().filter(author__id__in=lst)
    profile = Profile.objects.get(user=request.user)
    paginator = Paginator(qs, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False

    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()
    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
        'posts': posts
    }
    return render(request, 'posts/main2.html', context)
@login_required
def favourites_list(request):
    user = request.user
    posts = user.favourite.all()
    return render(request, 'posts/favourites.html', {'posts': posts})
@login_required
def favourite_add(request, id):
    post = get_object_or_404(Post, id=id)

    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value='Like'
            post_obj.save()
            like.save()

    return redirect(request.META.get('HTTP_REFERER'))

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('main-post-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post in order to delete')
        return obj

class PostUpdateView(LoginRequiredMixin,UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, 'You need to be the author of the post in order to delete')
            return super().form_valid(form)

def searchbar(request):
    if request.method=='GET':
        print('hello')
        search = request.GET.get('q')
        # profiles = Profile.objects.all().filter(Q(first_name__icontains=search) | Q(last_name__icontains=search) | Q(user__username__icontains=search))
        profiles = Profile.objects.filter(user__username__icontains=search)    
        return render(request)

posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages%}
            {% if 'warning' in message.tags %}
                <div class="ui negative message">
                    <div class="header">
                        {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the post?</p>
                <button type="submit">Submit</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

posts/templates/posts/favourites.html
{% extends 'base.html' %}
{% load static %}
{% block title %}favourites page{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<h1>My Favourites</h1>
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in posts %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>

                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}>
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'like-post-view' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        {% if profile not in obj.liked.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% endif %}
                    </form>
                <form action="{% url 'like-post-view' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        {% if profile not in obj.favorite.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                            </button>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                            </button>
                        {% endif %}

                </form>
                    <div class="col-md-7 d-flex justify-content-between">
                        <div>
                            <a href="{% url 'favourite-add' obj.id %} " class="btn btn-outline-primary">Remove</a>
                        </div>
                    </div>
                </div>

                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div>
                <a href="#">
                        <i class="bi bi-star"></i>
                </a>
            </div>
            <div class="extra content">
                <div class="mb-5">

                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}

                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>

                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>


        {% endfor %}
    </div>
   </div>
<div class="pagination">
    {% if posts.has_previous %}
        <a href="{% url 'main-post-view'%}?page={{ posts.previous_page_number}}" class="pagination-action">
            <button type="button" class="btn btn-primary">Previous</button>
        </a>
    {% endif %}
    {% if posts.has_next %}
        <a href="{% url 'main-post-view'%}?page={{ posts.next_page_number}}"><button type="button" class="btn btn-primary">Next</button></a>
    {% endif %}
</div>
{% endblock content %}

{% block scripts %}
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }
            });
        });
    </script>
{% endblock scripts %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% block title %}
posts
{% endblock %}
{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="eleven wide column">
            {% for obj in qs %}
            <div class="ui fluid card">
                <div class="content">
                   {{ obj.content }}
                </div>
                <div class="content">
                  <form action="{% url 'like-post-view' %}" method="POST">
                      {% csrf_token %}
                     <input type="hidden" name="post_id" value="{{obj.id}}">
                    <button type="submit" class="ui primary button">
                        {% if profile not in obj.liked.all %}
                            <i class="thumbs up icon"></i>&nbsp;Like
                        {% else %}
                            <i class="thumbs down icon"></i>&nbsp;Unlike
                        {% endif %}

                    </button>
                      &nbsp;{{obj.num_likes}}
                  </form>
                </div>
                <div>
                    {%if obj.comment_set.all %}
                        {% for c in obj.comment_set.all %}
                            <p>{{ c.body }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <form action="" method="POST" class="ui form">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{obj.id}}">
                    {{ c_form }}
                    <button type="submit" class="ui primary button" name="submit_c_form">comment</button>
                </form>
            </div>
            {% endfor %}
        </div>
        <div class="five wide column">
            {% if post_added %}
            <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ p_form }}
                <button type="submit" class="ui button positive" name="submit_p_form">Send Post</button>
            </form>
        </div>
        </row>
    </div>
{% endblock %}

posts/templates/posts/main2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}main page{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<div class="ui grid">
    <div class="eleven wide column">
        {% if not posts.object_list %}
        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                        <h1 style="text-align: center;">No posts yet . . .</h1>
                </div>
            </div>
        </div>
        {% endif %}
        {% for obj in posts.object_list %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                <a href="{% url 'profiles:profile-detail-view' obj.author.slug%}">{{ obj.author.user }}</a> - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'like-post-view' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        {% if profile not in obj.liked.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% endif %}
                    </form>
                <form action="{% url 'like-post-view' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        {% if profile not in obj.favorite.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                            </button>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="far fa-heart"></i>
                            </button>
                        {% endif %}

                </form>
                    <div class="col-md-7 d-flex justify-content-between">
                        <div>
                            <a href="{% url 'favourite-add' obj.id %} " class="btn btn-outline-primary">Add to Favourites</a>
                        </div>
                    </div>
                </div>

                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Send</button>
            </form>
        </div>
    </div>
</div>
<div class="pagination">
    {% if posts.has_previous %}
        <a href="{% url 'main-post-view'%}?page={{ posts.previous_page_number}}" class="pagination-action">
            <button type="button" class="btn btn-primary">Previous</button>
        </a>
    {% endif %}
    {% if posts.has_next %}
        <a href="{% url 'main-post-view'%}?page={{ posts.next_page_number}}"><button type="button" class="btn btn-primary">Next</button></a>
    {% endif %}
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
        });
    </script>
{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
update post
{% endblock %}

{% block content %}
    <div class="ui segment">
        <h3>Update post</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="ui button primary mt-5">Update</button>

        </form>

    </div>
{% endblock %}